"""i'm back baby!

Revision ID: d24c5c32afde
Revises: 
Create Date: 2022-09-04 18:47:56.402672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24c5c32afde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_obra', sa.String(length=64), nullable=True),
    sa.Column('calle_obra', sa.String(length=64), nullable=True),
    sa.Column('numero_obra', sa.Integer(), nullable=True),
    sa.Column('colonia_obra', sa.String(length=64), nullable=True),
    sa.Column('municipio_obra', sa.String(length=64), nullable=True),
    sa.Column('estado_obra', sa.String(length=64), nullable=True),
    sa.Column('cp_obra', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obras_calle_obra'), 'obras', ['calle_obra'], unique=False)
    op.create_index(op.f('ix_obras_colonia_obra'), 'obras', ['colonia_obra'], unique=False)
    op.create_index(op.f('ix_obras_cp_obra'), 'obras', ['cp_obra'], unique=False)
    op.create_index(op.f('ix_obras_estado_obra'), 'obras', ['estado_obra'], unique=False)
    op.create_index(op.f('ix_obras_municipio_obra'), 'obras', ['municipio_obra'], unique=False)
    op.create_index(op.f('ix_obras_nombre_obra'), 'obras', ['nombre_obra'], unique=True)
    op.create_index(op.f('ix_obras_numero_obra'), 'obras', ['numero_obra'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_obras_numero_obra'), table_name='obras')
    op.drop_index(op.f('ix_obras_nombre_obra'), table_name='obras')
    op.drop_index(op.f('ix_obras_municipio_obra'), table_name='obras')
    op.drop_index(op.f('ix_obras_estado_obra'), table_name='obras')
    op.drop_index(op.f('ix_obras_cp_obra'), table_name='obras')
    op.drop_index(op.f('ix_obras_colonia_obra'), table_name='obras')
    op.drop_index(op.f('ix_obras_calle_obra'), table_name='obras')
    op.drop_table('obras')
    # ### end Alembic commands ###
